name: Publish to Docker Hub

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get latest version
        run: |
          curl -s https://api.github.com/repos/pocketbase/pocketbase/releases/latest \
            | grep "tag_name" \
            | awk '{print $2}' \
            | tr -d '"' \
            | tr -d ',' \
            | tr -d 'v' \
            | tr -d ' ' \
            >> $VERSION
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sernhandler/pocketbase:latest
            sernhandler/pocketbase:$VERSION
          build-args: |
            VERSION=$VERSION